import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';

// export const metadata = {
//   title: 'Uncram.com',
//   description: 'Generated by create next app',
// };

export default function Layout({ children }) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
