import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import StoreContextProvider from '@/context/StoreContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Uncram.com',
  icons: {
    icon: '/logo.png', // or .png/.svg
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreContextProvider>{children}</StoreContextProvider>
      </body>
    </html>
  );
}
